### ISSUE TITLE
Extension advised for opened ruby `Gemfile.lock`

### ISSUE THREAD

**Issue by ShockwaveNN** [mariusschulz/vscode-yarn-lock-syntax#1]
Hi, I'm not sure if it possible but can `Gemfile.lock` be excluded pattern for your extension?

**Comment by mariusschulz** [comment]
Hi @ShockwaveNN, good catch! I just published v0.1.3 — could you please check if that fixed the issue?

**Comment by ShockwaveNN** [comment]
@mariusschulz yep, seems fine to me now, thank you
