### ISSUE TITLE
Support for Yarn 2 lockfiles

### ISSUE THREAD

**Issue by derekschinke** [mariusschulz/vscode-yarn-lock-syntax#2]
This doesn't support `yarn.lock` files generated by Yarn 2, as the syntax has changed

**Comment by mariusschulz** [comment]
Indeed, the syntax has changed with Yarn 2. Would you be interested in sending a PR? :)

**Comment by derekschinke** [comment]
I can try, although I have no idea where to start. I'll start playing around with it!

**Comment by mariusschulz** [comment]
Closing this issue as #3 now implements support for Yarn 2.
